name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Project setup
        run: npm install --force
      - name: Compile for production
        run: npm run prod
      - name: Upload ftp
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: dist/
          server: s019.cyon.net
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
